# Learn Posture

use machine learning to recognize robot's posture (following the example in [scikit-learn-intro.ipynb](./scikit-learn-intro.ipynb) )

## 1. Data collection

We have colleceted data before, you need to add new data if you want to add new posture.

* the dateset are in *robot_pose_data* folder
* each file contains the data belongs to this posture, e.g. the data in *Back* file are collected when robot was in "Back" posture
* the data file can be load by ```pickle```, e.g. ```pickle.load(open('Back'))```, the data is a list of feature data
* the features (e.g. each row of the data) are ['LHipYawPitch', 'LHipRoll', 'LHipPitch', 'LKneePitch', 'RHipYawPitch', 'RHipRoll', 'RHipPitch', 'RKneePitch', 'AngleX', 'AngleY'], where 'AngleX' and 'AngleY' are body angle (e.g. ```Perception.imu```) and others are joint angles.

## 2. Data preprocessing

In [1]:
%pylab inline
import pickle
from os import listdir, path
import numpy as np
from sklearn import svm, metrics

ROBOT_POSE_DATA_DIR = 'robot_pose_data'

Populating the interactive namespace from numpy and matplotlib


In [2]:
classes = listdir(ROBOT_POSE_DATA_DIR)
print classes

['HeadBack', 'Left', 'Right', 'Crouch', 'Knee', 'Stand', 'Sit', 'StandInit', 'Frog', 'Back', 'Belly']


In [66]:
def load_pose_data(i):
    '''load pose data from file'''
    data = []
    target = []
    # YOUR CODE HERE
    
    filename = path.join(ROBOT_POSE_DATA_DIR, classes[i])
    data = pickle.load(open(filename))
    target = [i] * len(data)
    
    return data, target
# print data

[[0.06600403785705566, 0.0061779022216796875, 0.07980990409851074, 2.0079641342163086, 0.06600403785705566, 0.0844118595123291, 0.09506607055664062, 1.8976001739501953, -0.018579784780740738, 1.4904650449752808], [0.06600403785705566, 0.007711887359619141, 0.07827591896057129, 2.0079641342163086, 0.06600403785705566, 0.08594608306884766, 0.09353208541870117, 1.8976001739501953, -0.018579784780740738, 1.490273356437683], [0.06600403785705566, 0.0061779022216796875, 0.07827591896057129, 2.0079641342163086, 0.06600403785705566, 0.08594608306884766, 0.09506607055664062, 1.8960661888122559, -0.018579784780740738, 1.490273356437683], [0.06600403785705566, 0.007711887359619141, 0.07827591896057129, 2.009498119354248, 0.06600403785705566, 0.0844118595123291, 0.09506607055664062, 1.8976001739501953, -0.018771473318338394, 1.4900816679000854], [0.06600403785705566, 0.0061779022216796875, 0.07827591896057129, 2.0079641342163086, 0.06600403785705566, 0.0844118595123291, 0.09506607055664062, 1.8960

In [68]:
# load all the data
all_data = []
all_target = []
# YOUR CODE HERE
for i in range(len(classes)):
    data, target = load_pose_data(i) 
    all_data = all_data + data
    all_target = all_target + target
print 'total number of data', len(all_data)
print 'total number of target', len(all_target)
# print all_data

total number of data 222
total number of target 222


In [65]:
# shuffule data
permutation = np.random.permutation(len(all_data))
n_training_data = int(len(all_data) * 0.7)
training_data = permutation[:n_training_data]
print training_data

[119 219  18   3 201 166  13 221 148 102  43 162 180  49 108 188  28 106
 153 107 181  27  96  10   1 131  58 100 170 157  23  25 146 176   6 115
  33 110  59 163 141 126   7   9 215 145 150  50 178 152  87  94  76 197
  47  17 192 183 128  72 159  67 149   8 195 147  19 165 174 155 123  30
 168 133  63 164  42 132 142 173 125  77  56 156  26 138  81  45 193  86
 187 217 186  69  55 111 171  89  78 143 204 144  93  37 122  51  66 209
  22  14 113 185  80 167 194  62 114  21   2 203  99 211 160 220 118   4
  41 116 184 161 212 190  64  12 199 134 208  54  53   5 109  24  34  15
  73 117  61  20 112  65  91 124 154  11  74]


## 3. Learn on training data

In scikit-learn, an estimator for classification is a Python object that implements the methods fit(X, y) and predict(T). An example of an estimator is the class sklearn.svm.SVC that implements support vector classification.

In [16]:
clf = svm.SVC(gamma=0.001, C=100.)

### learning

In [102]:
# YOUR CODE HERE
clf.fit(np.array(all_data)[training_data], np.array(all_target)[training_data])

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

### predicting

In [103]:
clf.predict(all_data[-1:]), all_target[-1:]

(array([10]), [10])

In [104]:
def evaluate(expected, predicted):
    print("Classification report:\n%s\n" % metrics.classification_report(expected, predicted))

    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

In [105]:
expected = []
predicted = []
# YOUR CODE HERE
expected = np.array(all_target)[training_data]
predicted = clf.predict(np.array(all_data)[training_data])
evaluate(expected, predicted)

Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00        22
           4       1.00      1.00      1.00         7
           5       1.00      1.00      1.00         5
           6       1.00      1.00      1.00        18
           7       1.00      1.00      1.00        39
           8       1.00      1.00      1.00         6
           9       1.00      1.00      1.00        16
          10       1.00      1.00      1.00        11

   micro avg       1.00      1.00      1.00       155
   macro avg       1.00      1.00      1.00       155
weighted avg       1.00      1.00      1.00       155


Confusion matrix:
[[ 9  0  0  0  0  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0  0  0  0]
 [ 0  0  0 22  0  0  0  0  0  0  0]
 

## 4. Evaluate on the test data

In [106]:
expected = []
predicted = []
# YOUR CODE HERE

test_data = permutation[n_training_data:]
test_data.shape
expected = np.asarray(all_target)[test_data]
predicted = clf.predict(np.asarray(all_data)[test_data])
evaluate(expected, predicted)

Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2
           2       1.00      0.86      0.92         7
           3       0.89      1.00      0.94         8
           4       1.00      1.00      1.00         3
           5       1.00      1.00      1.00         6
           6       1.00      1.00      1.00         8
           7       1.00      1.00      1.00        13
           8       1.00      1.00      1.00         4
           9       1.00      1.00      1.00         7
          10       1.00      1.00      1.00         8

   micro avg       0.99      0.99      0.99        67
   macro avg       0.99      0.99      0.99        67
weighted avg       0.99      0.99      0.98        67


Confusion matrix:
[[ 1  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  6  1  0  0  0  0  0  0  0]
 [ 0  0  0  8  0  0  0  0  0  0  0]
 

## 5. Deploy to the real system

We can simple use `pickle` module to serialize the trained classifier.

In [107]:
import pickle
ROBOT_POSE_CLF = 'robot_pose.pkl'
pickle.dump(clf, open(ROBOT_POSE_CLF, 'w'))

Then, in the application we can load the trained classifier again.

In [113]:
clf2 = pickle.load(open(ROBOT_POSE_CLF))
clf2.predict(all_data[-1:]), all_target[-1:]

(array([10]), [10])

In [111]:
all_data[-1:]

[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.5707963267948966]]

In [117]:
joint_names =  ['LHipYawPitch', 'LHipRoll', 'LHipPitch', 'LKneePitch', 'RHipYawPitch', 'RHipRoll', 'RHipPitch', 'RKneePitch']
joints = {'HeadYaw': -0.0, 'RHipPitch': -0.0, 'RElbowYaw': -0.0, 'RShoulderPitch': 0.0, 'LShoulderPitch': 0.0, 'LKneePitch': -0.0, 'RAnkleRoll': 0.0, 'LShoulderRoll': 0.008726646259971648, 'LHipPitch': -0.0, 'LElbowYaw': 0.0, 'LAnklePitch': -0.0, 'RHipYawPitch': -0.0, 'HeadPitch': 0.0, 'LElbowRoll': -0.008726646259971648, 'RShoulderRoll': -0.008726646259971648, 'LAnkleRoll': -0.0, 'LHipYawPitch': -0.0, 'RAnklePitch': -0.0, 'LHipRoll': -0.0, 'RHipRoll': 0.0, 'RElbowRoll': 0.008726646259971648, 'RKneePitch': -0.0}

values = []
for joint_name in joint_names:
    values.append(joints[joint_name])
print(values)

[-0.0, -0.0, -0.0, -0.0, -0.0, 0.0, -0.0, -0.0]
